### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by backupandforkacc** [tomasmetal23/Issabel#1]
Many thanks for the nice project. 

I am a bit confused by the instructions, can you please help me what to do? Do I have to run all the steps:

```
$ docker run --privileged --restart=always --name issabel -v /sys/fs/cgroup:/sys/fs/cgroup:ro -dti --hostname pbx  deathmetall/issabel:latest
$ docker exec -it issabel ./install.sh

$ docker commit issabel deathmetall/issabel:live
$ docker rm -f issabel

$ docker run --restart=always --name issabel \
        --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
        -v issabel-etc:/etc -v issabel-data:/var/lib \
        -dti --hostname pbx.saiyans.com.ve --network host \
       deathmetall/issabel:live
```

What is with the docker-compose.yml? Is that an alternative to anything of the steps above? I am used to used either `docker run` oder `docker-compose up `command to get a container running.

**Comment by tomasmetal23** [comment]
Is the documentation about the subject.


https://hub.docker.com/r/deathmetall/issabel

https://blog.saiyans.com.ve/2020/09/25/pbx-issabel-despliegue-con-docker/
